Dozentenplanung/Models/ExamType.cs
using System;
namespace Dozentenplanung.Models
{
    public class ExamType : BaseObject
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool IsDummy { get; set; }

        public bool DeleteFromContext(ApplicationDbContext aContext)
        {
            //Delete the receiver if is no dummy object
            if (this.IsDummy) {
                return false;
            } else {
                aContext.ExamTypes.Remove(this);
                return true;
            }
        }

        public static void CreateDummyInContext(ApplicationDbContext aContext) {
            ExamTypeBuilder builder = new ExamTypeBuilder(aContext);
            builder.Title = "Keine Prüfung";
            builder.IsDummy = true;
            builder.Save();
        }
    }
}

Dozentenplanung/Controllers/ExamTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dozentenplanung.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace Dozentenplanung.Controllers
{
    public class ExamTypeController : BaseController
    {
        public ExamTypeController(ApplicationDbContext aContext, UserManager<ApplicationUser> aUserManager, SignInManager<ApplicationUser> aSignInManager, IHttpContextAccessor httpContextAccessor) : base(aContext, aUserManager, aSignInManager, httpContextAccessor)
        {
        }


        public IActionResult Index()
        {
            this.PutRolesInViewBag();
            return View("examTypes", this.DatabaseContext.ExamTypes);
        }

        public IActionResult Edit(int? id)
        {
            if (this.CurrentUserIsAdministrator())
            {
                ExamType examType;
                if (id.HasValue)
                {
                    examType = this.DatabaseContext.ExamTypeForId(id.Value);
                }
                else
                {
                    ExamTypeBuilder examTypeBuilder = new ExamTypeBuilder(this.DatabaseContext);
                    examTypeBuilder.Title = "Neue Prüfungsart";
                    examTypeBuilder.Save();
                    examType = examTypeBuilder.ExamType();
                }
                return View(examType);
            } else {
                return RedirectToAction("index");
            }
        }

        public IActionResult Save(int id, string title, string description)
        {
            if (this.CurrentUserIsAdministrator()) {
                ExamTypeBuilder builder = new ExamTypeBuilder(this.DatabaseContext, this.DatabaseContext.ExamTypeForId(id));
                builder.Title = title;
                builder.Save();    
            }
            return RedirectToAction("index");
        }

        public IActionResult Delete(int id)
        {
            if (this.CurrentUserIsAdministrator()) {
                ExamType examType = this.DatabaseContext.ExamTypeForId(id);
                examType.DeleteFromContext(this.DatabaseContext);
                this.SaveDatabaseContext();    
            }
            return RedirectToAction("index");
        }
    }
}

Dozentenplanung/Views/ExamType/Edit.cshtml
@model Dozentenplanung.Models.ExamType
@{
    ViewData["title"] = "Prüfungsarten";
    ViewData["menuId"] = "examTypes";
}

<form id="form" asp-action="save" asp-controller="ExamType" asp-route-id="@Model.Id">
    <div class="columns">
        <div class="column">
            <div class="field">
                <label class="label">Bezeichnung</label>
                <div class="control">
                    @Html.EditorFor(examType => examType.Title, new { htmlAttributes = new { @class = "input" } })
                </div>
            </div>
        </div>
    </div>
    <a asp-controller="ExamType" asp-action="delete" asp-route-id="@Model.Id" class="button is-danger">Löschen</a>
    <button type="submit" class="button is-success" form="form">Speichern</button>
</form>

Dozentenplanung/Views/ExamType/ExamTypes.cshtml
@model IEnumerable<Dozentenplanung.Models.ExamType>
@{
    ViewData["title"] = "Prüfungsarten";
    ViewData["menuId"] = "examTypes";
}

@if (ViewBag.IsAdministrator) {
    <a asp-controller="ExamType" asp-action="edit" class="button is-success">Prüfungsart erstellen</a>
}

<table class="table is-fullwidth is-hoverable is-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th />
        </tr>
    </thead>
    @foreach (var eachType in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => eachType.Title)
            </td>
            <td>
                @if (ViewBag.IsAdministrator) {
                    <a class="button" asp-controller="ExamType" asp-action="edit" asp-route-id="@eachType.Id">Bearbeiten</a>
                }
            </td>
        </tr>
    }
</table>