Dozentenplanung/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dozentenplanung.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace Dozentenplanung.Controllers
{
    [Authorize]
    public class ModuleController : BaseController
    {
        public ModuleController(ApplicationDbContext aContext, UserManager<ApplicationUser> aUserManager, SignInManager<ApplicationUser> aSignInManager, IHttpContextAccessor httpContextAccessor) : base(aContext, aUserManager, aSignInManager, httpContextAccessor)
        {
        }

        public IActionResult Index()
        {
            ModuleSearch moduleSearch = new ModuleSearch(this.DatabaseContext);
            this.PutRolesInViewBag();
            return View(moduleSearch.Search());
        }
        public IActionResult Module(int id)
        {
            this.PutRolesInViewBag();
            return View(this.ModuleForId(id));
        }
        public IActionResult Edit (int? id, int? courseId)
        {
            if (this.CurrentUserCanWrite()) {
                Module theModule;
                if (id.HasValue)
                {
                    theModule = DatabaseContext.Modules.Find(id);
                }
                else
                {
                    ModuleBuilder builder = new ModuleBuilder(this.DatabaseContext);
                    builder.Course = this.CourseForId(courseId.Value);
                    builder.Designation = "Modulbezeichnung";
                    builder.Title = "Modultitel";
                    builder.Save();
                    theModule = builder.Module();
                }

                return View(theModule);    
            } else {
                return RedirectToAction("index");
            }
        }

        public IActionResult Delete(int id) {
            Module module = this.ModuleForId(id);
            if (this.CurrentUserCanWrite()) {
                module.DeleteFromContext(this.DatabaseContext);
                this.SaveDatabaseContext();   
            }
            return RedirectToAction("course", "course", new { id = module.CourseId });
        }

        [HttpPost]
        public IActionResult SaveModule(int id, int courseId, string title, string designation)
        {
            if (this.CurrentUserCanWrite()) {
                Module module = this.ModuleForId(id);
                ModuleBuilder moduleBuilder = new ModuleBuilder(this.DatabaseContext, module);
                moduleBuilder.Title = title;
                moduleBuilder.Designation = designation;
                moduleBuilder.Save();
                return RedirectToAction("course", "course", new { id = module.CourseId });
            } else {
                return RedirectToAction("index");
            }

        }


        private Module ModuleForId(int anId) {
            //Answer the module with the given id
            return this.DatabaseContext.ModuleForId(anId);
        }
    }
}

Dozentenplanung/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Dozentenplanung.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Dozentenplanung.Controllers
{
    [Authorize]
    public class UnitController : BaseController
    {
        public UnitController(ApplicationDbContext aContext, UserManager<ApplicationUser> aUserManager, SignInManager<ApplicationUser> aSignInManager, IHttpContextAccessor httpContextAccessor) : base(aContext, aUserManager, aSignInManager, httpContextAccessor)
        {
        }

        public IActionResult Index(string designation, string title, int? semester, DateTime? beginDate, DateTime? endDate, int? lecturerId, string status, string courseDesignation)
        {
            UnitSearch unitSearch = new UnitSearch(this.DatabaseContext);
            unitSearch.Designation = designation;
            unitSearch.Title = title;
            unitSearch.Semester = semester;
            unitSearch.BeginDate = beginDate;
            unitSearch.EndDate = endDate;
            unitSearch.LecturerId = lecturerId;
            unitSearch.SetStatus(status);
            unitSearch.CourseDesignation = courseDesignation;
            LecturerSearch lecturerSearch = new LecturerSearch(this.DatabaseContext);
            lecturerSearch.ShowDummyAll = true;
            lecturerSearch.ShowDummyNone = true;
            ViewBag.Lecturers = lecturerSearch.Search().Select(eachLecturer => new SelectListItem
            {
                Text = eachLecturer.Fullname,
                Value = eachLecturer.Id.ToString(),
                Selected = (lecturerId.HasValue && eachLecturer.Id == lecturerId.Value) || (!lecturerId.HasValue && eachLecturer.IsDummyAll)
            });

            ViewBag.UnitTitle = title;
            ViewBag.Designation = designation;
            ViewBag.Semester = semester;
            if (beginDate.HasValue) { ViewBag.BeginDate = beginDate.Value.ToString("yyyy-MM-dd"); }
            if (endDate.HasValue) { ViewBag.EndDate = endDate.Value.ToString("yyyy-MM-dd"); }
            ViewBag.Status = status;
            ViewBag.CourseDesignation = courseDesignation;
            this.PutRolesInViewBag();
            return View(unitSearch.Search());
        }

        public IActionResult Edit(int? id, int? moduleId) {
            if (this.CurrentUserCanWrite()) {
                Unit unit;
                if (id.HasValue)
                {
                    unit = this.DatabaseContext.UnitForId(id.Value);
                }
                else
                {
                    UnitBuilder unitBuilder = new UnitBuilder(this.DatabaseContext);
                    unitBuilder.Title = "";
                    unitBuilder.Designation = "Unitbezeichnung";
                    unitBuilder.Module = this.DatabaseContext.ModuleForId(moduleId.Value);
                    unitBuilder.Save();
                    unit = unitBuilder.Unit();
                }
                List<SelectListItem> theSkills = new List<SelectListItem>();
                foreach (Skill eachSkill in this.DatabaseContext.Skills)
                {
                    SelectListItem listItem = new SelectListItem();
                    listItem.Text = eachSkill.Title;
                    listItem.Value = eachSkill.Id.ToString();
                    listItem.Selected = unit.HasSkill(eachSkill);
                    theSkills.Add(listItem);
                }
                ViewBag.Skills = theSkills;
                ViewBag.SuitableLecturers = this.DatabaseContext.LecturersWithSkills().Select(eachLecturer => new SelectListItem
                {
                    Text = eachLecturer.StringForUnit(unit),
                    Value = eachLecturer.Id.ToString(),
                    Selected = eachLecturer.Id == unit.LecturerId
                });
                ViewBag.ExamTypes = this.DatabaseContext.ExamTypes.Select(eachExamType => new SelectListItem
                {
                    Text = eachExamType.Title,
                    Value = eachExamType.Id.ToString(),
                    Selected = eachExamType.Id == unit.ExamTypeId
                });
                return View(unit);  
            } else {
                return RedirectToAction("index");
            }

        }

        public IActionResult Unit(int id) {
            this.PutRolesInViewBag();
            return View(this.DatabaseContext.UnitForId(id));
        }

        [HttpPost]
        public IActionResult Save(int id, string title, string designation, int lecturer, List<int> SkillIds, int Semester, DateTime BeginDate, DateTime EndDate, int DurationOfExam, int ExamType, int status) {
            if (this.CurrentUserCanWrite()) {
                this.CreateBuilderAndSave(id, title, designation, lecturer, SkillIds, Semester, BeginDate, EndDate, DurationOfExam, ExamType, status);
                return RedirectToAction("unit", "unit", new { id = id });    
            } else {
                return RedirectToAction("index");
            }
        }

        [HttpPost]
        public IActionResult SetSkills(int id, string title, string designation, int lecturer, List<int> SkillIds, int Semester, DateTime BeginDate, DateTime EndDate, int DurationOfExam, int ExamType, int status) {
            this.CreateBuilderAndSave(id, title, designation, lecturer, SkillIds, Semester, BeginDate, EndDate, DurationOfExam, ExamType, status);
            return RedirectToAction("edit", "unit", new { id = id });
        }

        public IActionResult Delete(int id) {
            if (this.CurrentUserCanWrite()) {
                Unit unit = this.DatabaseContext.UnitForId(id);
                unit.DeleteFromContext(this.DatabaseContext);
                this.SaveDatabaseContext();
                return RedirectToAction("module", "module", new { id = unit.ModuleId });   
            } else {
                return RedirectToAction("index");
            }
        }

        private void CreateBuilderAndSave(int id, string title, string designation, int lecturer, List<int> SkillIds, int Semester, DateTime BeginDate, DateTime EndDate, int DurationOfExam, int ExamType, int status) {
            //Create a bilder with the given attributes and save the change
            UnitBuilder unitBuilder = new UnitBuilder(this.DatabaseContext, this.DatabaseContext.UnitForId(id));
            unitBuilder.Title = title;
            unitBuilder.Designation = designation;
            unitBuilder.Lecturer = this.DatabaseContext.LecturerForId(lecturer);
            unitBuilder.Semester = Semester;
            unitBuilder.BeginDate = BeginDate;
            unitBuilder.EndDate = EndDate;
            unitBuilder.ExamType = this.DatabaseContext.ExamTypeForId(ExamType);
            unitBuilder.DurationOfExam = DurationOfExam;
            unitBuilder.Status = status;
            List<Skill> skillList = new List<Skill>();
            foreach (int eachId in SkillIds)
            {
                skillList.Add(this.DatabaseContext.SkillForId(eachId));
            }
            unitBuilder.Skills = skillList;
            unitBuilder.Save();
        }
    }
}

Dozentenplanung/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["title"] - Dozentenplanung</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" rel="stylesheet" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
    <link href="/css/app.css" rel="stylesheet" />
    <meta charset="UTF-8" />

    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/css/selectize.min.css'>

</head>
<body>
    <div class="sidenav">
        <aside class="menu">
            <p class="menu-label">
                Dozenten
            </p>
            <ul class="menu-list">
                <li><a id="lecturers" asp-controller="lecturer" asp-action="index">Dozenten</a></li>
            </ul>
            <p class="menu-label">
                Vorlesung
            </p>
            <ul class="menu-list">
                <li><a id="courses" asp-controller="course" asp-action="index">Kurse</a></li>
                <li>
                    <ul>
                        <li><a id="modules" asp-controller="Module" asp-action="Index">Module</a></li>
                        <li><a id="units" asp-controller="Unit" asp-action="Index">Units</a></li>
                    </ul>
                </li>
            </ul>
            <p class="menu-label">
                Admin
            </p>
            <ul class="menu-list">
                <li><a id="skills" asp-controller="skill" asp-action="index">Skills</a></li>
                <li><a id="examTypes" asp-controller="examType" asp-action="index">Prüfungsarten</a></li>
                <li><a id="dev" asp-controller="dev" asp-action="index">Entwicklung</a></li>
            </ul>
            <p class="menu-label">
                Profil
            </p>
            <ul class="menu-list">
                <li><a id="profile" asp-controller="profile" asp-action="index">Profil</a></li>
                <li><a asp-controller="account" asp-action="logout">Logout</a></li>
            </ul>
        </aside>
    </div>

    <div class="main">
        <div id="contentContainer">
            <h2 class="title is-h2">@ViewData["title"]</h2>
            @RenderBody()
        </div>
    </div>
    <script>
            $("#" + "@ViewData["menuId"]").addClass("is-active");
    </script>
    @RenderSection("script", false)
    <script src='https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/standalone/selectize.min.js'></script>

</body>


</html>